# Generated by Django 3.2.5 on 2022-06-03 03:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0006_auto_20220603_0313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('title', 'owner')},
        ),
    ]
